// Cosmic Desk — Bridge scene renderer implementation.
//
// Pure SDL2 (no ImGui dependency). Layer SVGs are rasterized into SDL textures
// with lunasvg on resize; the background gradient and the 44 twinkles are
// generated procedurally to replicate the prototype exactly.

#include "ui/bridge/scene.h"

#include <lunasvg.h>

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <memory>
#include <string>
#include <vector>

#include "ui/bridge/design.h"
#include "ui/scale.h"

namespace cosmic::ui::scene {

namespace {

// One parallax layer: the SVG file name, its depth (parallax weight), the
// prototype's ex/ey pixel offsets and es scale, and the base alpha. reflex.svg
// is the exception: its alpha is driven per-frame by the glint value instead.
struct Layer {
    const char* name;
    float depth;
    float ex;
    float ey;
    float es;
    float alpha;
};

// Draw order = array order (back -> front). Values from the handoff README
// parallax table and the prototype's data-ex/ey/es attributes.
constexpr Layer kLayers[] = {
    {"nebula.svg",      12.0f,   0.0f, -14.0f, 1.04f, 0.96f},
    {"stars-far.svg",   10.0f,   0.0f, -10.0f, 1.03f, 1.00f},
    {"stars-mid.svg",   20.0f,   0.0f, -20.0f, 1.05f, 1.00f},
    {"planets.svg",     13.0f,   0.0f, -32.0f, 1.02f, 1.00f},
    {"desk.svg",        26.0f,   0.0f,  10.0f, 1.03f, 1.00f},
    {"monitor.svg",     26.0f,   0.0f,  10.0f, 1.03f, 1.00f},
    {"screen-logo.svg", 26.0f,   0.0f,  10.0f, 1.03f, 1.00f},
    {"obj-g11.svg",     26.0f,   0.0f,  10.0f, 1.03f, 1.00f},
    {"obj-g18.svg",     26.0f,   0.0f,  10.0f, 1.03f, 1.00f},
    {"obj-g22.svg",     26.0f,   0.0f,  10.0f, 1.03f, 1.00f},
    {"obj-g24.svg",     26.0f,   0.0f,  10.0f, 1.03f, 1.00f},
    {"obj-g33.svg",     26.0f,   0.0f,  10.0f, 1.03f, 1.00f},
    {"reflex.svg",      26.0f,   0.0f,  10.0f, 1.03f, 1.00f},
};
constexpr int kLayerCount = static_cast<int>(sizeof(kLayers) / sizeof(kLayers[0]));

// The reflex layer is the only one whose alpha is animated per frame.
constexpr int kReflexIndex = kLayerCount - 1;

// One twinkle dot, generated by the seeded LCG below.
struct Twinkle {
    float x;        // 0..1 across the viewport
    float y;        // 0..1 down the viewport
    float size;     // design px (multiplied by scale() at draw time)
    float period;   // seconds
    float delay;    // seconds
};

// Module state. All textures are owned here and rebuilt on resize.
struct State {
    bool initialized = false;
    int tex_w = 0;   // last rasterized texture size (0 = never)
    int tex_h = 0;
    SDL_Texture* layers[kLayerCount] = {};
    SDL_Texture* bg = nullptr;
    std::vector<Twinkle> twinkles;
    float cx = 0.0f;  // smoothed cursor, -1..1
    float cy = 0.0f;
};

State g_state;

// Logs a message to stderr (the Debug build keeps a console for log output).
void LogError(const char* msg) {
    std::fprintf(stderr, "[scene] %s\n", msg);
}

// Destroys a texture and nulls the slot. Safe on null.
void DestroyTexture(SDL_Texture*& tex) {
    if (tex != nullptr) {
        SDL_DestroyTexture(tex);
        tex = nullptr;
    }
}

// Linear interpolation between two 0xRRGGBBAA design tokens, producing a
// 0xAARRGGBB pixel (alpha in the MSB) as SDL_PIXELFORMAT_ARGB8888 expects.
uint32_t LerpColor(uint32_t from, uint32_t to, float t) {
    const auto lerp = [t](uint8_t ca, uint8_t cb) {
        return static_cast<uint8_t>(static_cast<float>(ca) +
                                    (static_cast<float>(cb) - static_cast<float>(ca)) * t);
    };
    const uint8_t r = lerp(static_cast<uint8_t>((from >> 24) & 0xFF),
                           static_cast<uint8_t>((to >> 24) & 0xFF));
    const uint8_t g = lerp(static_cast<uint8_t>((from >> 16) & 0xFF),
                           static_cast<uint8_t>((to >> 16) & 0xFF));
    const uint8_t b = lerp(static_cast<uint8_t>((from >> 8) & 0xFF),
                           static_cast<uint8_t>((to >> 8) & 0xFF));
    return 0xFF000000u | (static_cast<uint32_t>(r) << 16) |
           (static_cast<uint32_t>(g) << 8) | static_cast<uint32_t>(b);
}

// Rasterizes one layer SVG into a texture at (tex_w, tex_h). Returns null on
// any failure (after logging); the caller keeps the slot null.
SDL_Texture* RasterizeLayer(SDL_Renderer* renderer, const Layer& layer, int tex_w,
                            int tex_h) {
    char* base = SDL_GetBasePath();
    if (base == nullptr) {
        LogError("SDL_GetBasePath failed");
        return nullptr;
    }
    const std::string path = std::string(base) + "assets/ui/layers/" + layer.name;
    SDL_free(base);

    std::unique_ptr<lunasvg::Document> doc = lunasvg::Document::loadFromFile(path);
    if (!doc) {
        std::fprintf(stderr, "[scene] failed to load %s\n", path.c_str());
        return nullptr;
    }

    // lunasvg renders through plutovg, whose pixels are PREMULTIPLIED alpha
    // (0xAARRGGBB with the color channels already multiplied by alpha). SDL's
    // SDL_BLENDMODE_BLEND expects STRAIGHT alpha, so we must un-premultiply
    // before upload or the layers would look dark and muddy where translucent.
    lunasvg::Bitmap bitmap = doc->renderToBitmap(tex_w, tex_h, 0x00000000);
    if (bitmap.width() != tex_w || bitmap.height() != tex_h) {
        LogError("lunasvg rendered at an unexpected size");
        return nullptr;
    }

    std::vector<uint32_t> pixels(static_cast<size_t>(tex_w) * tex_h);
    const uint8_t* src = bitmap.data();
    for (size_t i = 0; i < pixels.size(); ++i) {
        const uint32_t v = static_cast<uint32_t>(src[i * 4]) |
                           (static_cast<uint32_t>(src[i * 4 + 1]) << 8) |
                           (static_cast<uint32_t>(src[i * 4 + 2]) << 16) |
                           (static_cast<uint32_t>(src[i * 4 + 3]) << 24);
        const uint32_t a = (v >> 24) & 0xFF;
        if (a == 0) {
            pixels[i] = 0;
            continue;
        }
        // Un-premultiply with rounding: straight = (premul * 255 + a/2) / a.
        auto un = [a](uint32_t c) {
            return std::min(255u, (c * 255u + a / 2u) / a);
        };
        const uint32_t r = un((v >> 16) & 0xFF);
        const uint32_t g = un((v >> 8) & 0xFF);
        const uint32_t b = un(v & 0xFF);
        pixels[i] = (a << 24) | (r << 16) | (g << 8) | b;
    }

    SDL_Texture* tex = SDL_CreateTexture(renderer, SDL_PIXELFORMAT_ARGB8888,
                                         SDL_TEXTUREACCESS_STATIC, tex_w, tex_h);
    if (tex == nullptr) {
        std::fprintf(stderr, "[scene] SDL_CreateTexture failed: %s\n", SDL_GetError());
        return nullptr;
    }
    if (SDL_UpdateTexture(tex, nullptr, pixels.data(), tex_w * 4) != 0) {
        std::fprintf(stderr, "[scene] SDL_UpdateTexture failed: %s\n", SDL_GetError());
        SDL_DestroyTexture(tex);
        return nullptr;
    }
    SDL_SetTextureBlendMode(tex, SDL_BLENDMODE_BLEND);
    // reflex.svg's alpha mod (1.0 -> 255) is overridden per-frame via glint.
    SDL_SetTextureAlphaMod(tex, static_cast<Uint8>(layer.alpha * 255.0f));
    return tex;
}

// Builds the procedural radial-gradient background texture at (tex_w, tex_h).
// Replicates `radial-gradient(60% 55% at 53% 42%, #1e2140 0%, #161834 55%,
// #101226 100%)`.
SDL_Texture* BuildBackground(SDL_Renderer* renderer, int tex_w, int tex_h) {
    std::vector<uint32_t> pixels(static_cast<size_t>(tex_w) * tex_h);
    for (int y = 0; y < tex_h; ++y) {
        for (int x = 0; x < tex_w; ++x) {
            // Normalized distance from the gradient center (53%, 42%) scaled
            // by the ellipse radii (60% w, 55% h).
            const float dx = (static_cast<float>(x) - 0.53f * tex_w) / (0.60f * tex_w);
            const float dy = (static_cast<float>(y) - 0.42f * tex_h) / (0.55f * tex_h);
            const float d = std::hypot(dx, dy);
            uint32_t color;
            if (d < 0.55f) {
                color = LerpColor(kBgGradCenter, kBgGradMid, d / 0.55f);
            } else {
                color = LerpColor(kBgGradMid, kBg, (d - 0.55f) / 0.45f);
            }
            pixels[static_cast<size_t>(y) * tex_w + x] = color;
        }
    }

    SDL_Texture* tex = SDL_CreateTexture(renderer, SDL_PIXELFORMAT_ARGB8888,
                                         SDL_TEXTUREACCESS_STATIC, tex_w, tex_h);
    if (tex == nullptr) {
        std::fprintf(stderr, "[scene] SDL_CreateTexture (bg) failed: %s\n", SDL_GetError());
        return nullptr;
    }
    if (SDL_UpdateTexture(tex, nullptr, pixels.data(), tex_w * 4) != 0) {
        std::fprintf(stderr, "[scene] SDL_UpdateTexture (bg) failed: %s\n", SDL_GetError());
        SDL_DestroyTexture(tex);
        return nullptr;
    }
    SDL_SetTextureBlendMode(tex, SDL_BLENDMODE_BLEND);
    return tex;
}

// Generates the 44 twinkle dots with the prototype's exact seeded LCG (seed 42).
void BuildTwinkles() {
    g_state.twinkles.clear();
    g_state.twinkles.reserve(44);

    uint64_t seed = 42;
    const auto rnd = [&seed]() {
        // 64-bit arithmetic: the prototype runs this LCG in JavaScript, where
        // the multiply is exact (doubles), so a 32-bit seed would wrap early
        // and diverge from it.
        seed = (seed * 16807u) % 2147483647u;
        return static_cast<float>(seed) / 2147483647.0f;
    };

    for (int i = 0; i < 44; ++i) {
        Twinkle t;
        t.size = 1.0f + rnd() * 2.2f;
        t.x = rnd();
        t.y = rnd();
        t.period = 2.0f + rnd() * 3.5f;
        t.delay = rnd() * 5.0f;
        g_state.twinkles.push_back(t);
    }
}

// Re-rasterizes every layer texture and the background at the given size.
// Destroys the old textures first. On any per-layer failure the slot stays
// null and the rest continue.
void RasterizeAll(SDL_Renderer* renderer, int tex_w, int tex_h) {
    for (int i = 0; i < kLayerCount; ++i) {
        DestroyTexture(g_state.layers[i]);
        g_state.layers[i] = RasterizeLayer(renderer, kLayers[i], tex_w, tex_h);
    }
    DestroyTexture(g_state.bg);
    g_state.bg = BuildBackground(renderer, tex_w, tex_h);
    g_state.tex_w = tex_w;
    g_state.tex_h = tex_h;
}

}  // namespace

void init(SDL_Renderer* renderer) {
    if (g_state.initialized) {
        return;
    }
    if (renderer == nullptr) {
        LogError("init called with a null renderer");
        return;
    }
    // Geometry draws (twinkles) use the blend path; set it once here and again
    // at the top of draw() because ImGui_ImplSDLRenderer2 resets its own state
    // each frame.
    SDL_SetRenderDrawBlendMode(renderer, SDL_BLENDMODE_BLEND);
    BuildTwinkles();
    g_state.initialized = true;
}

void shutdown(SDL_Renderer* renderer) {
    (void)renderer;
    for (int i = 0; i < kLayerCount; ++i) {
        DestroyTexture(g_state.layers[i]);
    }
    DestroyTexture(g_state.bg);
    g_state.tex_w = 0;
    g_state.tex_h = 0;
    g_state.twinkles.clear();
    g_state.cx = 0.0f;
    g_state.cy = 0.0f;
    g_state.initialized = false;
}

void draw(SDL_Renderer* renderer, int out_w, int out_h, const SceneInput& in) {
    if (renderer == nullptr || out_w <= 0 || out_h <= 0) {
        return;
    }
    if (!g_state.initialized) {
        init(renderer);
        if (!g_state.initialized) {
            return;
        }
    }

    // ImGui_ImplSDLRenderer2 sets its own blend state each frame, so re-assert
    // ours at the top of every draw. Leaving it set on return is harmless.
    SDL_SetRenderDrawBlendMode(renderer, SDL_BLENDMODE_BLEND);

    // 1. Smooth the cursor toward its target (prototype easing, ~60 fps).
    const float tx = 2.0f * in.mouse_x / static_cast<float>(out_w) - 1.0f;
    const float ty = 2.0f * in.mouse_y / static_cast<float>(out_h) - 1.0f;
    // ImGui reports the mouse position as (-FLT_MAX,-FLT_MAX) while the cursor
    // is outside the window. Easing toward that would poison the smoothed
    // cursor with -inf and then NaN, which NaN math can never recover from --
    // the scene would freeze or vanish permanently the first time the mouse
    // leaves the window. Hold the last smoothed position instead, matching the
    // prototype (it only updates on in-window mousemove events).
    if (std::isfinite(tx) && std::isfinite(ty)) {
        g_state.cx += (tx - g_state.cx) * 0.055f;
        g_state.cy += (ty - g_state.cy) * 0.055f;
    }

    // 2. Rasterize on resize (art box sized to the viewport).
    const float art_w = std::max(1.04f * out_w, 1.4f * out_h);
    const float art_h = art_w * 1200.0f / 1620.8481f;
    const int tex_w = static_cast<int>(std::ceil(art_w));
    const int tex_h = static_cast<int>(std::ceil(art_h));
    if (tex_w != g_state.tex_w || tex_h != g_state.tex_h) {
        RasterizeAll(renderer, tex_w, tex_h);
    }

    // 3. Background radial gradient, full viewport.
    if (g_state.bg != nullptr) {
        const SDL_Rect dst{0, 0, out_w, out_h};
        SDL_RenderCopy(renderer, g_state.bg, nullptr, &dst);
    }

    // 4. Twinkles (exact prototype replication).
    const float scale = cosmic::ui::scale();
    const SDL_Color text = SdlColor(kText);
    for (const Twinkle& t : g_state.twinkles) {
        const float phase = std::fmod((in.time_s + t.delay) / t.period, 1.0f);
        // Ease-in-out sine matching the CSS twk keyframes (0%/100% .12, 50% .9).
        const float o = 0.12f + 0.78f * (0.5f - 0.5f * std::cosf(2.0f * 3.14159265f * phase));
        const float size = t.size * scale;
        const SDL_Rect rect{
            static_cast<int>(t.x * out_w),
            static_cast<int>(t.y * out_h),
            static_cast<int>(size),
            static_cast<int>(size),
        };
        SDL_SetRenderDrawColor(renderer, text.r, text.g, text.b,
                               static_cast<Uint8>(o * 255.0f));
        SDL_RenderFillRect(renderer, &rect);
    }

    // 5. Layer pass, back -> front.
    // Guard motion like the easing above: U5 will animate it, and a non-finite
    // value would re-poison every dest rect the same way the mouse NaN did.
    const float motion = std::isfinite(in.motion) ? in.motion : 1.0f;
    const float cx = g_state.cx * motion;
    const float cy = g_state.cy * motion;
    for (int i = 0; i < kLayerCount; ++i) {
        SDL_Texture* tex = g_state.layers[i];
        if (tex == nullptr) {
            continue;
        }
        const Layer& layer = kLayers[i];

        // reflex.svg alpha is driven per-frame by the glint value.
        if (i == kReflexIndex) {
            const float glint =
                std::clamp(0.5f + 1.4f * g_state.cx - 0.6f * g_state.cy, 0.0f, 1.0f);
            SDL_SetTextureAlphaMod(tex, static_cast<Uint8>(glint * glint * 255.0f));
        }

        const float w = art_w * layer.es;
        const float h = art_h * layer.es;
        const float ox = layer.ex - cx * layer.depth;
        const float oy = layer.ey - cy * layer.depth;
        const SDL_FRect dest{
            static_cast<float>(out_w) / 2.0f - w / 2.0f + ox,
            static_cast<float>(out_h) / 2.0f - h / 2.0f + oy,
            w,
            h,
        };
        SDL_RenderCopyF(renderer, tex, nullptr, &dest);
    }
}

}  // namespace cosmic::ui::scene
